name: Continuous Integration

on:
  push:
    branches-ignore:
      - main   # Don't run CI on main branch (use CD workflow there)
  pull_request:
    branches:
      - "**"   # Run on all PRs

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run lint
      - name: Run ESLint
        run: npm run lint --if-present

      # Run tests
      - name: Run Tests
        run: npm test --if-present

      # Build project
      - name: Build Next.js App
        run: npm run build